### PR TITLE
Fix frequent ssl renewals

### LINKED ISSUE #46: Certificates are requested every two days
Currently the script renews the issued certificate every two days, which seems quite odd. Shouldn't the script check for how long the certificate is valid and just renew it roughly 30 days before expiry.

### PR DESCRIPTION
**Pull request by tilosp**
Before, the script renewed the cert as soon as it was older than two days.
This lead to many unnecessary renewals.
Now it only renews if it expires in less than 30 days (same as certbot).

Fixes https://github.com/freeipa/freeipa-letsencrypt/issues/46

### CODE REVIEW

**Comment by rcritten** [comment]
Thanks for the patch.

Can you add more information into the commit message as to what this fixes? It doesn't need to be a book. A line or two is find.
Can you add signed-off-by (git commit -s) as well?

File: renew-le.sh [hunk 1]
```diff
@@ -5,14 +5,14 @@ WORKDIR=$(dirname "$(realpath $0)")
 EMAIL=""
 
 ### cron
-# check that the cert will last at least 2 days from now to prevent too frequent renewal
+# check that the cert will last at least 30 days from now to prevent too frequent renewal
```
Comment (rcritten) [inline renew-le.sh]: I think this comment needs a re-write. It will trigger a renewal 30 days prior to expiration (or whatever value we come up with).

File: renew-le.sh [hunk 2]
```diff
@@ -5,14 +5,14 @@ WORKDIR=$(dirname "$(realpath $0)")
...
 # comment out this line for the first run
 if [ "${1:-renew}" != "--first-time" ]
 then
-	start_timestamp=`date +%s --date="$(openssl x509 -startdate -noout -in /var/lib/ipa/certs/httpd.crt | cut -d= -f2)"`
+	end_timestamp=`date +%s --date="$(openssl x509 -enddate -noout -in /var/lib/ipa/certs/httpd.crt | cut -d= -f2)"`
 	now_timestamp=`date +%s`
-	let diff=($now_timestamp-$start_timestamp)/86400
-	if [ "$diff" -lt "2" ]; then
+	let diff=($end_timestamp-$now_timestamp)/86400
+	if [ "$diff" -gt "30" ]; then
```
Comment (rcritten) [inline renew-le.sh:15]: Seems like 30 is a long time before expiration. LE sends me a renewal e-mail for my certs 19 days prior to renewal. How they came up with 19 I have no idea. 60 is definitely better than 2, but may be 21 days? Since this is/should be automated it will hopefully not fail too many times. I wonder if someone would notice anyway.

Comment (tilosp) [reply renew-le.sh:15]: that is whats certbot does

https://eff-certbot.readthedocs.io/en/latest/using.html#renewing-certificates
> This command attempts to renew any previously-obtained certificates that expire in less than 30 days.

**Comment by rcritten** [comment]
The changes look good, thanks.
