### PR TITLE
Move from mod_nss to mod_ssl

### LINKED ISSUE #12: Error: certutil: could not authenticate to token NSS Certificate DB.: SEC_ERROR_IO: An I/O error occurred during security authorization. (summary, doesn't work with 4.7.x)
I have executed script setup.sh from package "freeipa-letsencrypt".
The installation finished with this error message:
````
ipaplatform.redhat.tasks: INFO: Systemwide CA database updated.
ipalib.backend: DEBUG: Destroyed connection context.rpcclient_140228802354200
ipapython.admintool: INFO: The ipa-certupdate command was successful
certutil: could not authenticate to token NSS Certificate DB.: SEC_ERROR_IO: An I/O error
occurred during security authorization.
certutil: Server-Cert is neither a key-type nor a nickname nor a key-id: SEC_ERROR_IO: An
I/O error occurred during security authorization.
````
What's causing this error?
And how can I fix this?

The file "httpd-csr.der" in working directory (in my case /etc/ssl/ipa-le/) is 0
bytes. Therefore I conclude that the installation was not successful.
````
[root@ipa freeipa-letsencrypt]# ls -lR /etc/ssl/ipa-le/
/etc/ssl/ipa-le/:
insgesamt 0
drwxr-xr-x. 2 root root 187 3. Nov 19:49 ca
-rw-r-----. 1 root root 0 3. Nov 20:19 httpd-csr.der

/etc/ssl/ipa-le/ca:
insgesamt 24
-rw-r--r--. 1 root root 1220 3. Nov 19:49 DSTRootCAX3.pem
-rw-r--r--. 1 root root 1967 3. Nov 19:49 isrgrootx1.pem
-rw-r--r--. 1 root root 1702 3. Nov 19:49 LetsEncryptAuthorityX1.pem
-rw-r--r--. 1 root root 1675 3. Nov 19:49 LetsEncryptAuthorityX2.pem
-rw-r--r--. 1 root root 1647 3. Nov 19:49 LetsEncryptAuthorityX3.pem
-rw-r--r--. 1 root root 1647 3. Nov 19:49 LetsEncryptAuthorityX4.pem
````

THX

### PR DESCRIPTION
**Pull request by mkosek**
Convert all operations with certutil to openssl based ones, which are required from FreeIPA 4.7

Fixes: #12

### CODE REVIEW

File: renew-le.sh [hunk 1]
```diff
@@ -3,35 +3,37 @@ set -o nounset -o errexit
...
 # get a new cert
 letsencrypt certonly --standalone --csr "$WORKDIR/httpd-csr.der" --email "$EMAIL" --agree-tos
 
-# remove old cert
-certutil -D -d /etc/httpd/alias/ -n Server-Cert
-# add the new cert
-certutil -A -d /etc/httpd/alias/ -n Server-Cert -t u,u,u -a -i "$WORKDIR/0000_cert.pem"
+# replace the cert
+cp /var/lib/ipa/certs/httpd.crt /var/lib/ipa/certs/httpd.crt.bkp
+mv -f ~/0000_cert.pem /var/lib/ipa/certs/httpd.crt
```
Comment (abbra) [inline renew-le.sh]: does it have to be `~/0000_cert.pem`? In past it was in `$WORKDIR`

Comment (mkosek) [reply renew-le.sh]: It can be, fixed!

**Comment by abbra** [comment]
LGTM.
